sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  allow_failures:
    - php: nightly

before_script:
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - cd wp-tests/spec && bundle exec rspec test.rb

after_success: |
  if [ "$TRAVIS_BRANCH" == "development" ]; then
    repo_temp=$(mktemp -d)
    git clone "https://github.com/dCremins/add-ons" "$repo_temp"
    cd "$repo_temp"
    printf 'Checking out Master'
    git checkout master
    printf 'Merging %s\n' "$TRAVIS_COMMIT" >&2
    git merge --ff-only "$TRAVIS_COMMIT"
    printf 'Pushing to Add-Ons'
    git push "https://$DEPLOY_KEY@github.com/dCremins/add-ons" \
        "master" >/dev/null 2>&1
  fi
